import React, { useEffect, useState } from 'react';
import { Platform, View, Text, StyleSheet, ActivityIndicator } from 'react-native';
import { Tabs, Slot } from 'expo-router';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { MotiView } from 'moti';
import { Ionicons } from '@expo/vector-icons';

import { HapticTab } from '@/components/HapticTab';
import { IconSymbol } from '@/components/ui/IconSymbol';
import TabBarBackground from '@/components/ui/TabBarBackground';
import { Colors } from '@/constants/Colors';
import { useColorScheme } from '@/hooks/useColorScheme';

export default function TabLayout() {
	  const [isReady, setIsReady] = useState(false);
	    const colorScheme = useColorScheme();

	      useEffect(() => {
	      	    const init = async () => {
	      	    	      await new Promise(resolve => setTimeout(resolve, 1500));
	      	    	            setIsReady(true);
	      	    	                };
	      	    	                    init();
	      	    	                      }, []);

	      	    	                        if (!isReady) {
	      	    	                        	    return (
	      	    	                        	    	      <View style={styles.loadingContainer}>
	      	    	                        	    	              <Text style={styles.loadingText}>Carregando o Rendy...</Text>
	      	    	                        	    	                      <ActivityIndicator size="large" color="#0ff" />
	      	    	                        	    	                            </View>
	      	    	                        	    	                                );
	      	    	                        	    	                                  }

	      	    	                        	    	                                    return (
	      	    	                        	    	                                    	    <SafeAreaProvider>
	      	    	                        	    	                                    	          <View style={styles.container}>
	      	    	                        	    	                                    	                  <MotiView
	      	    	                        	    	                                    	                            from={{ opacity: 0, translateY: -20 }}
	      	    	                        	    	                                    	                                      animate={{ opacity: 1, translateY: 0 }}
	      	    	                        	    	                                    	                                                transition={{ type: 'timing', duration: 800 }}
	      	    	                        	    	                                    	                                                        >
	      	    	                        	    	                                    	                                                                  <Text style={styles.title}>Bem-vindo ao Rendy!</Text>
	      	    	                        	    	                                    	                                                                            <Text style={styles.subtitle}>Seu app inteligente, seguro e inovador</Text>
	      	    	                        	    	                                    	                                                                                    </MotiView>
	      	    	                        	    	                                    	                                                                                          </View>

	      	    	                        	    	                                    	                                                                                                <Tabs
	      	    	                        	    	                                    	                                                                                                        screenOptions={{
	      	    	                        	    	                                    	                                                                                                        	          tabBarActiveTintColor: Colors[colorScheme ?? 'light'].tint || '#0ff',
	      	    	                        	    	                                    	                                                                                                        	                    tabBarInactiveTintColor: '#888',
	      	    	                        	    	                                    	                                                                                                        	                              headerShown: false,
	      	    	                        	    	                                    	                                                                                                        	                                        tabBarButton: HapticTab,
	      	    	                        	    	                                    	                                                                                                        	                                                  tabBarBackground: TabBarBackground,
	      	    	                        	    	                                    	                                                                                                        	                                                            tabBarStyle: Platform.select({
	      	    	                        	    	                                    	                                                                                                        	                                                            	            ios: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	              position: 'absolute',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                          },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      default: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	              backgroundColor: '#000',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                            borderTopWidth: 0,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                        },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                  }),
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                          }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                >
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                        <Tabs.Screen
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                  name="index"
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            options={{
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	            title: 'Home',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        tabBarIcon: ({ color }) => (
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	              <IconSymbol size={28} name="house.fill" color={color} />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                          ),
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                    }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                            />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                    <Tabs.Screen
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                              name="explore"
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        options={{
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	            title: 'Explore',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        tabBarIcon: ({ color }) => (
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	              <IconSymbol size={28} name="paperplane.fill" color={color} />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                          ),
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                    }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                            />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                    <Tabs.Screen
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                              name="home"
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        options={{
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	            title: 'Início',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        tabBarIcon: ({ color, size }) => (
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	              <Ionicons name="home" size={size} color={color} />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                          ),
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                    }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                            />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                  </Tabs>

	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                        <Slot />
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                            </SafeAreaProvider>
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              );
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              }

	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              const styles = StyleSheet.create({
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  loadingContainer: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	    flex: 1,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	        backgroundColor: '#000',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	            justifyContent: 'center',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                alignItems: 'center',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                  },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    loadingText: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	    color: '#0ff',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	        fontSize: 18,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	            fontWeight: 'bold',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                marginBottom: 20,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                  },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    container: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	    backgroundColor: '#000',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	        alignItems: 'center',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	            justifyContent: 'center',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                padding: 20,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                  },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    title: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	    fontSize: 26,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	        color: '#0ff',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	            fontWeight: 'bold',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                textAlign: 'center',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                    marginBottom: 10,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                      },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        subtitle: {
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        	    fontSize: 16,
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        	        color: '#aaa',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        	            textAlign: 'center',
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        	              },
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        	              });
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    	                        }
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    	                    }
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    	                    }
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  	                    }
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              	  }
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        	                                                              })
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        	                        )
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        	                                                                        }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        	                        )
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        	                                                                        }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            	                        )
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      	                                                                                            }}
	      	    	                        	    	                                    	                                                                                                        	                                                            	            	                                      }
	      	    	                        	    	                                    	                                                                                                        	                                                            	            }
	      	    	                        	    	                                    	                                                                                                        	                                                            })
	      	    	                        	    	                                    	                                                                                                        }}
	      	    	                        	    	                                    )
	      	    	                        	    )
	      	    	                        }
	      	    }
	      })
}
